from .base import Brain
from .bo_cpg import BrainCPGBO
from .brain_nn import BrainNN
from .cpg import BrainCPG
from .cppn_cpg import BrainCPPNCPG
from .rlpower_splines import BrainRLPowerSplines
from .bo_cpg import BrainCPGBO
from .cpg import BrainCPG
from .cppn_cpg import BrainCPPNCPG
