# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tol.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tol.proto',
  package='tol',
  serialized_pb='\n\ttol.proto\x12\x03tol\"\x1f\n\tParameter\x12\x12\n\nparamValue\x18\x01 \x02(\x02\"\x7f\n\x08\x42odyPart\x12\n\n\x02id\x18\x01 \x02(\t\x12\x0c\n\x04type\x18\x02 \x02(\t\x12\x1d\n\x05param\x18\x03 \x03(\x0b\x32\x0e.tol.Parameter\x12\x13\n\x0borientation\x18\x04 \x02(\x05\x12%\n\x08\x63hildren\x18\x05 \x03(\x0b\x32\x13.tol.BodyConnection\"P\n\x0e\x42odyConnection\x12\x0f\n\x07srcSlot\x18\x01 \x02(\x05\x12\x10\n\x08\x64\x65stSlot\x18\x02 \x02(\x05\x12\x1b\n\x04part\x18\x03 \x02(\x0b\x32\r.tol.BodyPart\"#\n\x04\x42ody\x12\x1b\n\x04root\x18\x01 \x02(\x0b\x32\r.tol.BodyPart\"=\n\x10NeuralConnection\x12\x0b\n\x03src\x18\x01 \x02(\t\x12\x0c\n\x04\x64\x65st\x18\x02 \x02(\t\x12\x0e\n\x06weight\x18\x03 \x02(\x02\"\xa1\x01\n\x06Neuron\x12\n\n\x02id\x18\x01 \x02(\t\x12\r\n\x05layer\x18\x02 \x02(\t\x12\x0c\n\x04type\x18\x03 \x02(\t\x12\x0c\n\x04\x62ias\x18\x04 \x01(\x02\x12\x12\n\nbodyPartId\x18\x05 \x01(\t\x12\x0c\n\x04ioId\x18\x06 \x01(\x05\x12\x0b\n\x03tau\x18\x07 \x01(\x02\x12\x13\n\x0bphaseOffset\x18\x08 \x01(\x02\x12\x0e\n\x06period\x18\t \x01(\x02\x12\x0c\n\x04gain\x18\n \x01(\x02\"O\n\x05\x42rain\x12\x1b\n\x06neuron\x18\x01 \x03(\x0b\x32\x0b.tol.Neuron\x12)\n\nconnection\x18\x02 \x03(\x0b\x32\x15.tol.NeuralConnection\"G\n\x05Robot\x12\n\n\x02id\x18\x01 \x02(\x05\x12\x17\n\x04\x62ody\x18\x02 \x02(\x0b\x32\t.tol.Body\x12\x19\n\x05\x62rain\x18\x03 \x02(\x0b\x32\n.tol.Brain')




_PARAMETER = _descriptor.Descriptor(
  name='Parameter',
  full_name='tol.Parameter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='paramValue', full_name='tol.Parameter.paramValue', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=18,
  serialized_end=49,
)


_BODYPART = _descriptor.Descriptor(
  name='BodyPart',
  full_name='tol.BodyPart',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='tol.BodyPart.id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='tol.BodyPart.type', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='param', full_name='tol.BodyPart.param', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='orientation', full_name='tol.BodyPart.orientation', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='children', full_name='tol.BodyPart.children', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=51,
  serialized_end=178,
)


_BODYCONNECTION = _descriptor.Descriptor(
  name='BodyConnection',
  full_name='tol.BodyConnection',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='srcSlot', full_name='tol.BodyConnection.srcSlot', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='destSlot', full_name='tol.BodyConnection.destSlot', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='part', full_name='tol.BodyConnection.part', index=2,
      number=3, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=180,
  serialized_end=260,
)


_BODY = _descriptor.Descriptor(
  name='Body',
  full_name='tol.Body',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='root', full_name='tol.Body.root', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=262,
  serialized_end=297,
)


_NEURALCONNECTION = _descriptor.Descriptor(
  name='NeuralConnection',
  full_name='tol.NeuralConnection',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='src', full_name='tol.NeuralConnection.src', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dest', full_name='tol.NeuralConnection.dest', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='weight', full_name='tol.NeuralConnection.weight', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=299,
  serialized_end=360,
)


_NEURON = _descriptor.Descriptor(
  name='Neuron',
  full_name='tol.Neuron',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='tol.Neuron.id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='layer', full_name='tol.Neuron.layer', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='tol.Neuron.type', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bias', full_name='tol.Neuron.bias', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bodyPartId', full_name='tol.Neuron.bodyPartId', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ioId', full_name='tol.Neuron.ioId', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tau', full_name='tol.Neuron.tau', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='phaseOffset', full_name='tol.Neuron.phaseOffset', index=7,
      number=8, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='period', full_name='tol.Neuron.period', index=8,
      number=9, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gain', full_name='tol.Neuron.gain', index=9,
      number=10, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=363,
  serialized_end=524,
)


_BRAIN = _descriptor.Descriptor(
  name='Brain',
  full_name='tol.Brain',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='neuron', full_name='tol.Brain.neuron', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='connection', full_name='tol.Brain.connection', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=526,
  serialized_end=605,
)


_ROBOT = _descriptor.Descriptor(
  name='Robot',
  full_name='tol.Robot',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='tol.Robot.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='body', full_name='tol.Robot.body', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='brain', full_name='tol.Robot.brain', index=2,
      number=3, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=607,
  serialized_end=678,
)

_BODYPART.fields_by_name['param'].message_type = _PARAMETER
_BODYPART.fields_by_name['children'].message_type = _BODYCONNECTION
_BODYCONNECTION.fields_by_name['part'].message_type = _BODYPART
_BODY.fields_by_name['root'].message_type = _BODYPART
_BRAIN.fields_by_name['neuron'].message_type = _NEURON
_BRAIN.fields_by_name['connection'].message_type = _NEURALCONNECTION
_ROBOT.fields_by_name['body'].message_type = _BODY
_ROBOT.fields_by_name['brain'].message_type = _BRAIN
DESCRIPTOR.message_types_by_name['Parameter'] = _PARAMETER
DESCRIPTOR.message_types_by_name['BodyPart'] = _BODYPART
DESCRIPTOR.message_types_by_name['BodyConnection'] = _BODYCONNECTION
DESCRIPTOR.message_types_by_name['Body'] = _BODY
DESCRIPTOR.message_types_by_name['NeuralConnection'] = _NEURALCONNECTION
DESCRIPTOR.message_types_by_name['Neuron'] = _NEURON
DESCRIPTOR.message_types_by_name['Brain'] = _BRAIN
DESCRIPTOR.message_types_by_name['Robot'] = _ROBOT

class Parameter(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PARAMETER

  # @@protoc_insertion_point(class_scope:tol.Parameter)

class BodyPart(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _BODYPART

  # @@protoc_insertion_point(class_scope:tol.BodyPart)

class BodyConnection(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _BODYCONNECTION

  # @@protoc_insertion_point(class_scope:tol.BodyConnection)

class Body(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _BODY

  # @@protoc_insertion_point(class_scope:tol.Body)

class NeuralConnection(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _NEURALCONNECTION

  # @@protoc_insertion_point(class_scope:tol.NeuralConnection)

class Neuron(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _NEURON

  # @@protoc_insertion_point(class_scope:tol.Neuron)

class Brain(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _BRAIN

  # @@protoc_insertion_point(class_scope:tol.Brain)

class Robot(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ROBOT

  # @@protoc_insertion_point(class_scope:tol.Robot)


# @@protoc_insertion_point(module_scope)
