# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tolrg.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tolrg.proto',
  package='tolrg',
  serialized_pb='\n\x0btolrg.proto\x12\x05tolrg\"(\n\x12\x45volvableParameter\x12\x12\n\nparamValue\x18\x01 \x02(\x02\"z\n\x08\x42odyPart\x12\n\n\x02id\x18\x01 \x02(\t\x12\x0c\n\x04type\x18\x02 \x02(\t\x12\x0c\n\x04root\x18\x03 \x02(\x08\x12\x31\n\x0e\x65volvableParam\x18\x04 \x03(\x0b\x32\x19.tolrg.EvolvableParameter\x12\x13\n\x0borientation\x18\x05 \x02(\x05\"N\n\x0e\x42odyConnection\x12\x0b\n\x03src\x18\x01 \x02(\t\x12\x0c\n\x04\x64\x65st\x18\x02 \x02(\t\x12\x0f\n\x07srcSlot\x18\x03 \x02(\x05\x12\x10\n\x08\x64\x65stSlot\x18\x04 \x02(\x05\"P\n\x04\x42ody\x12\x1d\n\x04part\x18\x01 \x03(\x0b\x32\x0f.tolrg.BodyPart\x12)\n\nconnection\x18\x02 \x03(\x0b\x32\x15.tolrg.BodyConnection\"=\n\x10NeuralConnection\x12\x0b\n\x03src\x18\x01 \x02(\t\x12\x0c\n\x04\x64\x65st\x18\x02 \x02(\t\x12\x0e\n\x06weight\x18\x03 \x02(\x02\"\xa1\x01\n\x06Neuron\x12\n\n\x02id\x18\x01 \x02(\t\x12\r\n\x05layer\x18\x02 \x02(\t\x12\x0c\n\x04type\x18\x03 \x02(\t\x12\x0c\n\x04\x62ias\x18\x04 \x01(\x02\x12\x12\n\nbodyPartId\x18\x05 \x01(\t\x12\x0c\n\x04ioId\x18\x06 \x01(\x05\x12\x0b\n\x03tau\x18\x07 \x01(\x02\x12\x13\n\x0bphaseOffset\x18\x08 \x01(\x02\x12\x0e\n\x06period\x18\t \x01(\x02\x12\x0c\n\x04gain\x18\n \x01(\x02\"S\n\x05\x42rain\x12\x1d\n\x06neuron\x18\x01 \x03(\x0b\x32\r.tolrg.Neuron\x12+\n\nconnection\x18\x02 \x03(\x0b\x32\x17.tolrg.NeuralConnection\"K\n\x05Robot\x12\n\n\x02id\x18\x01 \x02(\x05\x12\x19\n\x04\x62ody\x18\x02 \x02(\x0b\x32\x0b.tolrg.Body\x12\x1b\n\x05\x62rain\x18\x03 \x02(\x0b\x32\x0c.tolrg.Brain')




_EVOLVABLEPARAMETER = _descriptor.Descriptor(
  name='EvolvableParameter',
  full_name='tolrg.EvolvableParameter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='paramValue', full_name='tolrg.EvolvableParameter.paramValue', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=22,
  serialized_end=62,
)


_BODYPART = _descriptor.Descriptor(
  name='BodyPart',
  full_name='tolrg.BodyPart',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='tolrg.BodyPart.id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='tolrg.BodyPart.type', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='root', full_name='tolrg.BodyPart.root', index=2,
      number=3, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='evolvableParam', full_name='tolrg.BodyPart.evolvableParam', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='orientation', full_name='tolrg.BodyPart.orientation', index=4,
      number=5, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=64,
  serialized_end=186,
)


_BODYCONNECTION = _descriptor.Descriptor(
  name='BodyConnection',
  full_name='tolrg.BodyConnection',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='src', full_name='tolrg.BodyConnection.src', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dest', full_name='tolrg.BodyConnection.dest', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='srcSlot', full_name='tolrg.BodyConnection.srcSlot', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='destSlot', full_name='tolrg.BodyConnection.destSlot', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=188,
  serialized_end=266,
)


_BODY = _descriptor.Descriptor(
  name='Body',
  full_name='tolrg.Body',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='part', full_name='tolrg.Body.part', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='connection', full_name='tolrg.Body.connection', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=268,
  serialized_end=348,
)


_NEURALCONNECTION = _descriptor.Descriptor(
  name='NeuralConnection',
  full_name='tolrg.NeuralConnection',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='src', full_name='tolrg.NeuralConnection.src', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dest', full_name='tolrg.NeuralConnection.dest', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='weight', full_name='tolrg.NeuralConnection.weight', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=350,
  serialized_end=411,
)


_NEURON = _descriptor.Descriptor(
  name='Neuron',
  full_name='tolrg.Neuron',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='tolrg.Neuron.id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='layer', full_name='tolrg.Neuron.layer', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='tolrg.Neuron.type', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bias', full_name='tolrg.Neuron.bias', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bodyPartId', full_name='tolrg.Neuron.bodyPartId', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ioId', full_name='tolrg.Neuron.ioId', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tau', full_name='tolrg.Neuron.tau', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='phaseOffset', full_name='tolrg.Neuron.phaseOffset', index=7,
      number=8, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='period', full_name='tolrg.Neuron.period', index=8,
      number=9, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gain', full_name='tolrg.Neuron.gain', index=9,
      number=10, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=414,
  serialized_end=575,
)


_BRAIN = _descriptor.Descriptor(
  name='Brain',
  full_name='tolrg.Brain',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='neuron', full_name='tolrg.Brain.neuron', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='connection', full_name='tolrg.Brain.connection', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=577,
  serialized_end=660,
)


_ROBOT = _descriptor.Descriptor(
  name='Robot',
  full_name='tolrg.Robot',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='tolrg.Robot.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='body', full_name='tolrg.Robot.body', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='brain', full_name='tolrg.Robot.brain', index=2,
      number=3, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=662,
  serialized_end=737,
)

_BODYPART.fields_by_name['evolvableParam'].message_type = _EVOLVABLEPARAMETER
_BODY.fields_by_name['part'].message_type = _BODYPART
_BODY.fields_by_name['connection'].message_type = _BODYCONNECTION
_BRAIN.fields_by_name['neuron'].message_type = _NEURON
_BRAIN.fields_by_name['connection'].message_type = _NEURALCONNECTION
_ROBOT.fields_by_name['body'].message_type = _BODY
_ROBOT.fields_by_name['brain'].message_type = _BRAIN
DESCRIPTOR.message_types_by_name['EvolvableParameter'] = _EVOLVABLEPARAMETER
DESCRIPTOR.message_types_by_name['BodyPart'] = _BODYPART
DESCRIPTOR.message_types_by_name['BodyConnection'] = _BODYCONNECTION
DESCRIPTOR.message_types_by_name['Body'] = _BODY
DESCRIPTOR.message_types_by_name['NeuralConnection'] = _NEURALCONNECTION
DESCRIPTOR.message_types_by_name['Neuron'] = _NEURON
DESCRIPTOR.message_types_by_name['Brain'] = _BRAIN
DESCRIPTOR.message_types_by_name['Robot'] = _ROBOT

class EvolvableParameter(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _EVOLVABLEPARAMETER

  # @@protoc_insertion_point(class_scope:tolrg.EvolvableParameter)

class BodyPart(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _BODYPART

  # @@protoc_insertion_point(class_scope:tolrg.BodyPart)

class BodyConnection(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _BODYCONNECTION

  # @@protoc_insertion_point(class_scope:tolrg.BodyConnection)

class Body(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _BODY

  # @@protoc_insertion_point(class_scope:tolrg.Body)

class NeuralConnection(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _NEURALCONNECTION

  # @@protoc_insertion_point(class_scope:tolrg.NeuralConnection)

class Neuron(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _NEURON

  # @@protoc_insertion_point(class_scope:tolrg.Neuron)

class Brain(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _BRAIN

  # @@protoc_insertion_point(class_scope:tolrg.Brain)

class Robot(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ROBOT

  # @@protoc_insertion_point(class_scope:tolrg.Robot)


# @@protoc_insertion_point(module_scope)
