#!/bin/sh
# Generate Python protobuf files
protoc -I ../cpp/revolve/msgs -I /usr/local/include/gazebo-6.5/gazebo/msgs/proto --python_out=../revolve/spec/msgs/ ../cpp/revolve/msgs/*.proto

# Correctly reference imported Gazebo messages
sed -i -E 's/import (vector3d|pose|time|model)_pb2/from pygazebo.msg import \1_pb2/g' ../revolve/spec/msgs/*.py
