#!/bin/sh
# Create build directory
mkdir -p ../build
cd ../build

# Run cmake and make to generate C++ files
cmake ../spec
make

# Generate Python files
protoc -I=../spec --python_out=. ../spec/tol.proto

# Copy files to source directories
cp tol.pb.cc ../spec/cpp
cp tol.pb.h ../spec/cpp
cp tol_pb2.py ../tolspec
